[package]
name = "eigen_rxx"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.31"

[build-dependencies]
miette = { version = "4.7.1", features = ["fancy"] }
approx = "0.5"
cc = "1.0.73"
