[tasks.wrapper]
command = "j2render.py"
args = ["-o", "src/wrapper.rs", "tpl/wrapper.rs"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["wrapper"]

[tasks.test]
command = "cargo"
args = ["test", "--", "--nocapture"]
dependencies = ["build"]